# Generated by Django 2.0.6 on 2019-03-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_collector_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
    ]
