# Generated by Django 2.0.6 on 2019-03-06 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_collector_app', '0002_remove_usermodel_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_date_made',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
