# Generated by Django 2.2 on 2019-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_collector_app', '0003_gamemodel_game_date_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
