# Generated by Django 2.2 on 2019-03-05 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('game_ageLimit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password1', models.CharField(default=0, max_length=50)),
                ('password2', models.CharField(default=0, max_length=50)),
                ('date_account_created', models.DateField(default=datetime.date.today)),
                ('rank', models.CharField(default='grunt', max_length=50)),
            ],
        ),
    ]
